import type { Combo, Fighter, Skill } from "./types";
export const asset = (name: string, frame = "271-15607", extension = "svg") =>
  `/combat/${frame}-${name}.${extension}`;
export const initialParty: Fighter[] = [
  {
    id: "p1",
    name: "Player 1 · you",
    role: "Mage",
    rank: 0,
    hp: 58,
    maxHp: 70,
    speed: 14,
    sprite: asset("imgHero4"),
  },
  {
    id: "p2",
    name: "Player 2",
    role: "Warrior",
    rank: 2,
    hp: 96,
    maxHp: 120,
    speed: 8,
    sprite: asset("imgHero5"),
  },
  {
    id: "p3",
    name: "Player 3",
    role: "Rogue",
    rank: 1,
    hp: 52,
    maxHp: 75,
    speed: 16,
    sprite: asset("imgHero6"),
  },
  {
    id: "p4",
    name: "Player 4",
    role: "Druid",
    rank: 0,
    hp: 64,
    maxHp: 80,
    speed: 11,
    sprite: asset("imgHero7"),
  },
];
export const initialEnemies: Fighter[] = [
  {
    id: "skeleton",
    name: "Skeleton warden",
    role: "lvl 8",
    rank: 0,
    hp: 88,
    maxHp: 110,
    speed: 9,
    sprite: asset("imgSkeleton"),
    state: "Soaked",
    intent: "Bone cleave",
    threat: "32 dmg · sets Off-balance",
  },
  {
    id: "slime",
    name: "Ember slime",
    role: "lvl 7",
    rank: 1,
    hp: 64,
    maxHp: 64,
    speed: 6,
    sprite: asset("imgSlime"),
    intent: "Fire breath",
    threat: "40 dmg · sets Burning 2t",
  },
  {
    id: "bat",
    name: "Cave bat",
    role: "lvl 6",
    rank: 2,
    hp: 30,
    maxHp: 40,
    speed: 19,
    sprite: asset("imgBat"),
    intent: "Screech",
    threat: "12 dmg · Blinded 1t",
  },
];
export const skills: Skill[] = [
  {
    id: "wave",
    name: "Wave",
    glyph: "W",
    speed: 12,
    tone: "water",
    target: "enemy",
    sets: "Soaked · 2t",
    damage: 12,
  },
  {
    id: "lightning",
    name: "Lightning",
    glyph: "L",
    speed: 14,
    tone: "arcane",
    target: "enemy",
    consumes: "Soaked",
    combo: "Electrocution",
    damage: 18,
  },
  {
    id: "fireball",
    name: "Fireball",
    glyph: "F",
    speed: 10,
    tone: "fire",
    target: "enemy",
    sets: "Burning · 2t",
    consumes: "Soaked",
    combo: "Steam",
    damage: 24,
  },
  {
    id: "arcane",
    name: "Arcane bolt",
    glyph: "A",
    speed: 18,
    tone: "blue",
    target: "enemy",
    damage: 16,
  },
  {
    id: "defend",
    name: "Defend",
    glyph: "D",
    speed: 0,
    tone: "green",
    target: "self",
    sets: "Defending · 1t",
    damage: 0,
  },
  {
    id: "swap",
    name: "Swap place",
    glyph: "⇄",
    speed: 20,
    tone: "muted",
    target: "ally",
    damage: 0,
  },
];
export const combos: Combo[] = [
  {
    name: "Electrocution",
    state: "Soaked",
    setter: "Wave · Mage",
    consumer: "Lightning · Mage",
    effect: "dmg ×2 · Stunned 1t",
    found: "turn 02 · P1",
    role: "Mage",
  },
  {
    name: "Steam",
    state: "Soaked",
    setter: "Rain call · Druid",
    consumer: "Fireball · Mage",
    effect: "Blinds every enemy 1t",
    found: "turn 01 · P1",
    role: "Mage",
  },
  {
    name: "Backstab",
    state: "Off-balance",
    setter: "Shield bash · Warrior",
    consumer: "Assassinate · Rogue",
    effect: "guaranteed critical",
    found: "turn 04 · P3",
    role: "Rogue",
  },
  {
    name: "Wildfire",
    state: "Burning",
    setter: "Fireball · Mage",
    consumer: "Gust · Druid",
    effect: "Burning 2t on every enemy",
    found: "turn 04 · P1 + P4",
    role: "Druid",
    secret: true,
  },
  {
    name: "Shatter",
    state: "Stunned",
    setter: "Lightning · Mage",
    consumer: "Shield bash · Warrior",
    effect: "armour −50 % · 2t",
    found: "turn 06 · P2",
    role: "Warrior",
  },
  {
    name: "Mudlock",
    state: "Soaked",
    setter: "Rain call · Druid",
    consumer: "Entangle · Druid",
    effect: "Rooted · cannot swap",
    found: "turn 07 · P4",
    role: "Druid",
  },
  {
    name: "Brand",
    state: "Marked",
    setter: "Shadow mark · Rogue",
    consumer: "Cleave · Warrior",
    effect: "hits whole rank",
    found: "turn 09 · P2",
    role: "Warrior",
  },
  ...["Burning", "Off-balance", "Stunned", "Blinded", "???"].map(
    (state, i) => ({
      name: "???",
      state,
      setter: "???",
      consumer: "???",
      effect: ["hint: something cold", "hint: a heavy fall"][i] ?? "—",
      found: "—",
      role: "Secret",
      unknown: true,
      secret: true,
    }),
  ),
];
export const rankNames = ["back rank", "mid rank", "front rank"];
